spring:
  rabbitmq:
    host: rabbitmq
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PW}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/service-app-realm

  mongodb:
    uri: mongodb://${PRICING_DB_USERNAME}:${PRICING_DB_PASSWORD}@pricing-service-db:27017/${PRICING_DB_NAME}?authSource=admin

eureka:
  client:
    service-url:
      defaultZone: http://service-app-registry:8761/eureka/